### ISSUE TITLE
make IPLib compatible with Python 3

### ISSUE THREAD

**Issue by opsdisk** [alberanid/python-iplib#1]
Hello,

I tried installing this on Python 3.6.5, Ubuntu 18.04.  Here's the output.

```bash
# python setup.py install
running install
running build
running build_py
creating build
creating build/lib
copying iplib.py -> build/lib
running build_scripts
creating build/scripts-3.6
copying and adjusting ./bin/cidrinfo -> build/scripts-3.6
copying and adjusting ./bin/ipconv -> build/scripts-3.6
copying and adjusting ./bin/nmconv -> build/scripts-3.6
changing mode of build/scripts-3.6/cidrinfo from 644 to 755
changing mode of build/scripts-3.6/ipconv from 644 to 755
changing mode of build/scripts-3.6/nmconv from 644 to 755
running install_lib
copying build/lib/iplib.py -> /home/user/project/.venv/lib/python3.6/site-packages
byte-compiling /home/user/project/.venv/lib/python3.6/site-packages/iplib.py to iplib.cpython-36.pyc
  File "/home/user/project/.venv/lib/python3.6/site-packages/iplib.py", line 83
    VALID_NETMASKS = {0: 0L, 1: 2147483648L, 2: 3221225472L, 3: 3758096384L,
                          ^
SyntaxError: invalid syntax

running install_scripts
copying build/scripts-3.6/cidrinfo -> /home/user/project/.venv/bin
copying build/scripts-3.6/nmconv -> /home/user/project/.venv/bin
copying build/scripts-3.6/ipconv -> /home/user/project/.venv/bin
changing mode of /home/user/project/.venv/bin/cidrinfo to 755
changing mode of /home/user/project/.venv/bin/nmconv to 755
changing mode of /home/user/project/.venv/bin/ipconv to 755
running install_egg_info
Writing /home/user/project/.venv/lib/python3.6/site-packages/iplib-1.1.egg-info

```

If you aren't still supporting this, do you know of another Python library that supports these functions?

```is_dot(ip): Return True if the IP address is in dotted decimal notation.
is_hex(ip): Return True if the IP address is in hexadecimal notation.
is_bin(ip): Return True if the IP address is in binary notation.
is_oct(ip): Return True if the IP address is in octal notation.
is_dec(ip): Return True if the IP address is in decimal notation```

**Comment by alberanid** [comment]
Hi @opsdisk , thanks for the report.
Right now IPLib is compatible with Python 2.x only (well, in fact it was written for Python 1.x).

I'm surely interested into porting it to Python 3.x, if possible staying compatible with Python 2.7.
It should not be a great effort; I hope to be able to look at it in the next few weeks, but can't make promises...

I'm not familiar with other libraries; Python 3 includes https://docs.python.org/3/library/ipaddress.html to manipulate IP addresses, but I doubt it has the same functions.

**Comment by opsdisk** [comment]
Thanks for the quick respsone @alberanid!  Python3 support would be great if you could find the time.  I was digging into the `ipaddress` library trying to find similar functionality, but came up empty-handed.  ~I'm also trying to find a library to convert from binary/octal/dec/hex into dotted quad.~ Just found the convert function, good stuff!

**Comment by alberanid** [comment]
well, damn rain... I fixed it (hopefully).

IPlib should now be compatible with both Python 2.7 and Python 3.x.

If you can, give it a try.

Thanks for the report!

**Comment by opsdisk** [comment]
Works great!  Thank you so much @alberanid for writing this library and the quick solution.  Tests passed without any errors.  Any plans on updating it pypi to this version?

**Comment by alberanid** [comment]
@opsdisk : done! https://pypi.org/project/iplib/

Thanks for the remind!

**Comment by opsdisk** [comment]
Thank you!
